### ISSUE TITLE
Dragging to specific element

### ISSUE THREAD

**Issue by mlflabs** [mystroken/drag#1]
Hello, thanks for a really good example, 

I was just wondering if I want to automatically move to a specific element, how would I get the coordinates of the element?

In other words, with all the elements, how do I get each elements position coordinates?

Thanks,

Mike

**Comment by mystroken** [comment]
Hello Mike,
Glad to read you ^^
First of all, let me remind you that the library is just a simple way to track each elementary "hold and drag" operation on a surface (a container).

Now taking all this into account, for your use case, you just have to build a whole independent system that uses the library.
Only your system knows about the elements you're talking about.
The system must initialize the library and accumulate each amount of "hold and drag" into a variable (just like the scrollTop variable of the window scroll event ;-) ).
When initializing the system, you must register all the elements in your container and their different positions (all elements must ideally have same size and with this logic you can easily calculate the exact position of each element in the container).

Then, on each "hold and drag" on your container, you can compare the current amount of dragged zone (since you're accumulating it) with each elements of the container (since you know their exact position in the container).

And voila! :-D


Hope I just helped you figuring out how you can implement what you want.
Let me know if I've been as clear as possible.

**Comment by mlflabs** [comment]
Thx for the reply, ill try it out

**Comment by mystroken** [comment]
Don't hesitate to contact me on twitter if you face issue with your code ;-)

NOTE: Don't forget to close this issue if you think that I solved your problem ^^
