### ISSUE TITLE
Not working on desktop touch

### ISSUE THREAD

**Issue by Chousse** [mystroken/drag#2]
Hi,
thanks for your lib. 
I'm trying to use it on a windows multitouchscreen (laptop Dell and iiyama 27") and touch/swipe not working at all, there's a options to activate it ?
thanks

**Comment by mystroken** [comment]
Hello
Thank you for considering using the library.

Indeed,
On the demo, 
I noticed a bug concerning the touch screens.
It was mistake from my side because I built the project with the 0.1.0 version of the library instead of the recent one (0.2.0).

Please could you confirm that the demo is now currently working on your device?
For your own project, make sure you use the latest version of the library.

**Comment by Chousse** [comment]
thanks for your response.
I tried to log that from drag.js
hasMouseEvent:true 
hasTouchEvent:false 
hasPointerEvent:false
hasTouchWinEvent:undefined
I think that's why but I dont figure why because it's a touchscreen

**Comment by Chousse** [comment]
Ok, if i force hasTouchEvent to TRUE, script working !

**Comment by Chousse** [comment]
So, the problem come from the touchevent detection, not from you code. 
Thanks
